# Generated by Django 6.0.2 on 2026-03-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useremail',
            old_name='usermail',
            new_name='email',
        ),
    ]
