# Generated by Django 6.0.2 on 2026-03-12 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='board',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='boards_app.board'),
        ),
    ]
