# Generated by Django 6.0.2 on 2026-03-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0002_boardmember_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='members',
            new_name='board_members',
        ),
    ]
