# Generated by Django 6.0.2 on 2026-03-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0003_rename_members_board_board_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board_members',
            new_name='members',
        ),
    ]
